### ISSUE TITLE
Don't run the loop with require

### ISSUE THREAD

**Issue by muschellij2** [andrew-leroux/rnhanesdata#2]
The R checking for packages doesn't work well with the loop of require statements you have.  For example, you had `plyr` in the loop, but `R CMD check` didn't find that as a missed dependency because it should be in a `library` command.

**Comment by andrew-leroux** [comment]
Fixed this issue so there's no note in the CRAN check. 

Still not passing the Travis Linux check -- I still think it's a file path issue.
