### ISSUE TITLE
Clarification Needed on NHANES exclusion criteria.

### ISSUE THREAD

**Issue by etzkorn** [andrew-leroux/rnhanesdata#6]
Hi Andrew, 

I was looking through your NHANES vignettes for a project, and I came across a section where I feel I needed some more detail to reproduce your results.

Specifically I am looking at https://andrew-leroux.github.io/rnhanesdata/articles/NHANES_accelerometry_introduction.html, section 5 that says:

From the total of 14631 exclude participants who were:

younger than 50 years old, or 85 and older at the time they wore the accelerometer (10859 participants);

missing BMI or education predictor variables (41 participants);

had fewer than 3 days of data with at least 10 hours of estimated wear time (517 participants);

missing mortality information (21 participants);

alive with follow up less than 5 years (0 participants);

missing systolic blood pressure, total cholesterol or HDL cholesterol measurements (293 participants).

The number of participants with missing data for all pairwise combinations of variables with missing data:

I’ve noticed that this section does not have any accompanying code, specifically the creation of the vector “Exclude” that is referenced in the next section:

```
## Create our dataset for analysis with one row per subject
## containing only those subjects who meet our inclusion criteria.
data_analysis  <- subset(table_dat, Exclude == 0)
## get adjusted survey weights using the reweight_accel function
data_analysis  <- reweight_accel(data_analysis)
```

To be really clear, are you (a) keeping individuals with at least 3 days each with at least 3 hours of estimated wear time? or (b) throwing out days that don’t have at least 10 hours of wear time, and THEN throwing out individuals who don’t have three days of data?

From your previous presentations, it seemed like you had done (b), but the vignette implies you did (a).

**Comment by andrew-leroux** [comment]
Hi Lacey,

I'm assuming for (a) you meant 10 hours, but correct me if I'm wrong. 

Procedurally, the steps in the vignette are consistent with (b). If you look at the markdown file: https://github.com/andrew-leroux/rnhanesdata/blob/master/vignettes/NHANES_accelerometry_introduction.Rmd starting at line 497 you see we first remove days with fewer than 10 hours of estimated wear time (lines 497-499), then identify those individuals with fewer than 3 days of data remaining (line 500) and exclude those individuals (line 511 + line 556).

Regardless, I'm not sure I understand the distinction between your (a) and (b). It seems to me like they achieve the same end result.

**Comment by etzkorn** [comment]
Yes I meant 10 hours. Thank you for referencing the markdown file--this gives the code I was missing from the .html file. I think in statement (a) (as I believe the current vignette is written), an individual who has 3 days with >10 hours of wear and a 4th day of 2 hours of wear would have all four days retained for the analysis. In (b) it is clearer that we do a two-step filtering of days and then participants. Thank you for your quick response!
